services:
  postgres:
    image: postgres:16
    container_name: users_postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "5431:5432"

    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 10
  liquibase:
    image: liquibase/liquibase:4.27
    container_name: users_liquibase
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./migrations:/liquibase/changelog:ro
    environment:
      LIQUIBASE_COMMAND_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      LIQUIBASE_COMMAND_USERNAME: ${POSTGRES_USER}
      LIQUIBASE_COMMAND_PASSWORD: ${POSTGRES_PASSWORD}
      LIQUIBASE_COMMAND_CHANGELOG_FILE: changelog/db.changelog-master.yaml
    command: ["update"]
    restart: "no"
  telegram-bot:
    build: .
    env_file:
      - .env
    environment:
      - CONFIG_PATH=/root/local.yaml
    ports:
      - "8080:8080"
    depends_on:
      - liquibase
volumes:
  pgdata:

