services:
  kafka:
    image: apache/kafka:4.2.0
    container_name: kafka
    networks:
      - techstream-common-net
    ports:
      - "9092:9092"
    environment:
      CLUSTER_ID: "644a7fd4-2a20-4685-a83c-c977cd4d88a2"
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /var/lib/kafka/data
    volumes:
      - kafka-kraft:/var/lib/kafka/data
    healthcheck:
      test: [ "CMD", "/opt/kafka/bin/kafka-topics.sh", "--bootstrap-server", "localhost:9092", "--list" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
  kafka-init:
    image: apache/kafka:4.2.0
    container_name: kafka-init
    networks:
      - techstream-common-net
    depends_on:
      kafka:
        condition: service_healthy
    restart: "no"
    entrypoint: [ "/bin/sh", "-c" ]
    command:
      - |
        echo "Waiting for Kafka to be ready..."
        echo "Creating topic 'orders', 'keys'..."
        /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9092 --create --if-not-exists --topic orders --partitions 3 --replication-factor 1
        /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9092 --create --if-not-exists --topic keys --partitions 3 --replication-factor 1
        echo "Topic created."

volumes:
  kafka-kraft:

networks:
  techstream-common-net:
    external: true